//WARNING: This Font is usable only with MikroE GLCD Lib.
//         X-GLCD Lib does not handle this font.

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroeElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : RK
//GLCD FontSize : 8 x 8

const unsigned short RK[] = {
        0xFF, 0xFF, 0x31, 0x31, 0x71, 0x51, 0xDF, 0x8E,  // Code for char R 
        0xFF, 0xFF, 0x18, 0x3C, 0x66, 0xC3, 0x81, 0x00   // Code for char K
        };

unsigned const char R_data[8] = {0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80};